on:
  push:
    branches:
      - main
  pull_request:
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        graalvm: [ 22.2.0 ]
        java: [ 11, 17 ]
    steps:
    - name: Test
      run: ./run_graalvm_test.sh
